# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4eeec87bbdbc512108dc9d447e5f21f7210aaf0b560557fef6d7eba24ce0537d50750b4f639688f6603aa1e1d19b961a05ef6af891122c9c30eaef33f918c21

test:
  secret_key_base: 6693b2b634ea0709d77c12e4ab2b65b429bd6d32f4718efbe2d76da97ab627676b2418355c9cc977bd683413b099d307528ac6dd2026bf5ea2037ae53d7dbf8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
